<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Анализатор страниц</title>

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.8/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-sRIl4kxILFvY47J16cr9ZwB07vP4J8+LH7qKQnuqkuIAvNWLzeN8tE5YBujZqJLB" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.8/dist/js/bootstrap.bundle.min.js" integrity="sha384-FKyoEForCGlyvwx9Hj09JcYn3nv7wiPVlz7YYwJrWVcXK/BmnVDxM+D2scQbITxI" crossorigin="anonymous"></script>
</head>
<body class="min-vh-100 d-flex flex-column">
    <?php require __DIR__ . '/../layout/header.phtml'; ?>
    <?php require __DIR__ . '/../layout/alerts.phtml'; ?>
    <main class="flex-grow-1">
        <div class="container-lg mt-3">
            <h1>Сайты</h1>
            <div class="table-responsive">
                <table class="table table-bordered table-hover text-nowrap" data-test="urls">
                    <thead>
                        <tr>
                            <th>ID</th>
                            <th>Имя</th>
                            <th>Последняя проверка</th>
                            <th>Код ответа</th>
                        </tr>
                    </thead>
                    <tbody>
                        <?php foreach ($urls as $url):?>
                        <tr>
                            <td><?= $url->getId()?></td>
                            <td><a href="/urls/<?= $url->getId()?>"><?= $url->getName()?></a></td>
                            <td></td>
                            <td></td>
                        </tr>
                        <?php endforeach; ?>
                    </tbody>
                </table>
            </div>
        </div>
    </main>
    <?php require __DIR__ . '/../layout/footer.phtml'; ?>
</body>
</html>
