<main class="flex-grow-1">
        <div class="container-lg mt-3">
            <h1>Сайты</h1>
            <div class="table-responsive">
                <table class="table table-bordered table-hover text-nowrap" data-test="urls">
                    <thead>
                        <tr>
                            <th>ID</th>
                            <th>Имя</th>
                            <th>Последняя проверка</th>
                            <th>Код ответа</th>
                        </tr>
                    </thead>
                    <tbody>
                        <?php foreach ($table as $row):?>
                        <tr>
                            <td><?= $row['id'] ?></td>
                            <td><a href="/urls/<?= $row['id'] ?>"><?= $row['name']?></a></td>
                            <td><?= $row['last_check'] ?></td>
                            <td><?= $row['last_status_code'] ?></td>
                        </tr>
                        <?php endforeach; ?>
                    </tbody>
                </table>
            </div>
        </div>
    </main>
