<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Анализатор страниц</title>

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.8/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-sRIl4kxILFvY47J16cr9ZwB07vP4J8+LH7qKQnuqkuIAvNWLzeN8tE5YBujZqJLB" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.8/dist/js/bootstrap.bundle.min.js" integrity="sha384-FKyoEForCGlyvwx9Hj09JcYn3nv7wiPVlz7YYwJrWVcXK/BmnVDxM+D2scQbITxI" crossorigin="anonymous"></script>
</head>
<body class="min-vh-100 d-flex flex-column">
    <header class="flex-shrink-0">
        <nav class="navbar navbar-expand-md navbar-dark bg-dark px-3">
            <a class="navbar-brand" href="/">Анализатор страниц</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNav">
                <ul class="navbar-nav">
                    <li class="nav-item">
                        <a href="/" class="nav-link">Главная</a>
                    </li>
                    <li class="nav-item">
                        <a href="/urls" class="nav-link">Сайты</a>
                    </li>
                </ul>
            </div>
        </nav>
    </header>
    <div class="alert alert-success">
        Страница успешно добавлена
    </div>
    <main class="flex-grow-1">
        <div class="container-lg mt-3">
            <h1>Сайт: <?= htmlspecialchars($url->getName()) ?></h1>
            <div class="table-responsive">
                <table class="table table-bordered table-hover text-nowrap" data-test="url">
                    <tbody>
                        <tr>
                            <td>ID</td>
                            <td><?= $url->getId() ?></td>
                        </tr>
                        <tr>
                            <td>Имя</td>
                            <td><?= htmlspecialchars($url->getName()) ?></td>
                        </tr>
                        <tr>
                            <td>Дата создания</td>
                            <td><?= $url->getCreatedAt()->toDateTimeString() ?></td>
                        </tr>
                    </tbody>
                </table>
            </div>
            <h2 class="mt-5 mb-3">Проверки</h2>
            <form method="post" action="/urls/1/checks" class="mb-3">
                <input type="submit" class="btn btn-primary" value="Запустить проверку">
            </form>
            <table class="table table-bordered table-hover" data-test="checks">
                <thead>
                    <tr>
                        <th>ID</th>
                        <th>Код ответа</th>
                        <th>h1</th>
                        <th>title</th>
                        <th>description</th>
                        <th>Дата создания</th>
                    </tr>
                </thead>
                <tbody> 
                    <tr>
                        <td>$check-1</td>
                        <td>$check-2</td>
                        <td class="text-break">$check-3</td>
                        <td class="text-break">$check-4</td>
                        <td class="text-break">$check-5</td>
                        <td>$check-6</td>
                    </tr>
                </tbody>
            </table>
        </div>
    </main>
    <footer class="border-top py-3 mt-5 flex-shrink-0">
        <div class="container-lg">
            <div class="text-center">
                <a href="https://hexlet.io/pages/about" target="_blank">Hexlet</a>
            </div>
        </div>

    </footer>
</body>
</html>