<main class="flex-grow-1">
        <div class="container-lg mt-3">
            <h1>Сайт: <?= htmlspecialchars($url->getName()) ?></h1>
            <div class="table-responsive">
                <table class="table table-bordered table-hover text-nowrap" data-test="url">
                    <tbody>
                        <tr>
                            <td>ID</td>
                            <td><?= $url->getId() ?></td>
                        </tr>
                        <tr>
                            <td>Имя</td>
                            <td><?= htmlspecialchars($url->getName()) ?></td>
                        </tr>
                        <tr>
                            <td>Дата создания</td>
                            <td><?= $url->getCreatedAt()->toDateTimeString() ?></td>
                        </tr>
                    </tbody>
                </table>
            </div>
            <h2 class="mt-5 mb-3">Проверки</h2>
            <form method="post" action="/urls/1/checks" class="mb-3">
                <input type="submit" class="btn btn-primary" value="Запустить проверку">
            </form>
            <table class="table table-bordered table-hover" data-test="checks">
                <thead>
                    <tr>
                        <th>ID</th>
                        <th>Код ответа</th>
                        <th>h1</th>
                        <th>title</th>
                        <th>description</th>
                        <th>Дата создания</th>
                    </tr>
                </thead>
                <tbody> 
                    <tr>
                        <td>$check-1</td>
                        <td>$check-2</td>
                        <td class="text-break">$check-3</td>
                        <td class="text-break">$check-4</td>
                        <td class="text-break">$check-5</td>
                        <td>$check-6</td>
                    </tr>
                </tbody>
            </table>
        </div>
    </main>