<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Анализатор страниц</title>

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.8/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-sRIl4kxILFvY47J16cr9ZwB07vP4J8+LH7qKQnuqkuIAvNWLzeN8tE5YBujZqJLB" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.8/dist/js/bootstrap.bundle.min.js" integrity="sha384-FKyoEForCGlyvwx9Hj09JcYn3nv7wiPVlz7YYwJrWVcXK/BmnVDxM+D2scQbITxI" crossorigin="anonymous"></script>
</head>
<body class="min-vh-100 d-flex flex-column">
    <?php require 'templates/layout/header.phtml'; ?>
    <?php require 'templates/layout/alerts.phtml'; ?>
    <main class="flex-grow-1">
        <div class="container-lg mt-3">
            <h1>Сайт: <?= htmlspecialchars($url->getName()) ?></h1>
            <div class="table-responsive">
                <table class="table table-bordered table-hover text-nowrap" data-test="url">
                    <tbody>
                        <tr>
                            <td>ID</td>
                            <td><?= $url->getId() ?></td>
                        </tr>
                        <tr>
                            <td>Имя</td>
                            <td><?= htmlspecialchars($url->getName()) ?></td>
                        </tr>
                        <tr>
                            <td>Дата создания</td>
                            <td><?= $url->getCreatedAt()->toDateTimeString() ?></td>
                        </tr>
                    </tbody>
                </table>
            </div>
            <h2 class="mt-5 mb-3">Проверки</h2>
            <form method="post" action="/urls/1/checks" class="mb-3">
                <input type="submit" class="btn btn-primary" value="Запустить проверку">
            </form>
            <table class="table table-bordered table-hover" data-test="checks">
                <thead>
                    <tr>
                        <th>ID</th>
                        <th>Код ответа</th>
                        <th>h1</th>
                        <th>title</th>
                        <th>description</th>
                        <th>Дата создания</th>
                    </tr>
                </thead>
                <tbody> 
                    <tr>
                        <td>$check-1</td>
                        <td>$check-2</td>
                        <td class="text-break">$check-3</td>
                        <td class="text-break">$check-4</td>
                        <td class="text-break">$check-5</td>
                        <td>$check-6</td>
                    </tr>
                </tbody>
            </table>
        </div>
    </main>
    <?php require 'templates/layout/footer.phtml'; ?>
</body>
</html>
