<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Анализатор страниц</title>

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.8/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-sRIl4kxILFvY47J16cr9ZwB07vP4J8+LH7qKQnuqkuIAvNWLzeN8tE5YBujZqJLB" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.8/dist/js/bootstrap.bundle.min.js" integrity="sha384-FKyoEForCGlyvwx9Hj09JcYn3nv7wiPVlz7YYwJrWVcXK/BmnVDxM+D2scQbITxI" crossorigin="anonymous"></script>
</head>
<body class="min-vh-100 d-flex flex-column">
    <?php require __DIR__ . '/layout/header.phtml'; ?>
    <?php require __DIR__ . '/layout/alerts.phtml'; ?>
    <main class="flex-grow-1">
        <div class="container-lg mt-3">
            <div class="row">
                <div class="col-12 col-md-10 col-lg-8 mx-auto border rounded-3 bg-light p-5">
                    <h1 class="display-3">Анализатор страниц</h1>
                    <p class="lead">Бесплатно проверяйте сайты на SEO пригодность</p>
                    <form action="/urls" method="post" class="row" required>
                        <div class="col-8">
                            <label for="text" class="visually-hidden">URL для проверки</label>
                            <?php if (!empty($errors)): ?>
                            <input type="text" name="url[name]" value="<?= htmlspecialchars($url['name']) ?>" class="form-control form-control-lg is-invalid"
                                placeholder="https://www.example.com">
                            <div class="invalid-feedback"><?= $errors[0] ?></div>
                            <?php else: ?>
                            <input type="text" name="url[name]" value="" class="form-control form-control-lg"
                                placeholder="https://www.example.com">
                            <?php endif; ?>
                        </div>
                        <div class="col-2">
                            <input type="submit" class="btn btn-primary btn-lg ms-3 px-5 text-uppercase mx-3"
                                value="Проверить">
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </main>
    <?php require __DIR__ . '/layout/footer.phtml'; ?>
</body>
</html>
